# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: my
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-dynamodb-local

functions:
  getSide:
    handler: build/handler.apiGet
    events:
      - http:
          path: /api/{proxy+}
          method: GET
  postSide:
    handler: build/handler.apiPost
    events:
      - http:
          path: /api/{proxy+}
          method: POST

resources:
  Resources:
    Animal:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: animals
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: created
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: idx_created
          KeySchema:
          - AttributeName: created
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 6666
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      # Uncomment only if you already have a DynamoDB running locally
      # noStart: true

    seed:
      test:
        sources:
          - table: animals
            rawsources: [./mock/animals.json]

  

